require 'faraday'
require 'rspec'
require 'json'
require 'base64'
require 'webmock/rspec'
require 'oauth'
require 'launchy'
require 'active_model'
require 'shoulda-matchers'
require 'bundler'

require 'user'
require 'tweet'
require 'friend'
require './env'